const incidents = [
  { "equipement_id": 1, "description": "Écran noir au démarrage", "statut": "ouvert", "gravite": "moyen" },
  { "equipement_id": 2, "description": "Bourrage papier", "statut": "résolu", "gravite": "faible" },
  { "equipement_id": 3, "description": "Connexion réseau instable", "statut": "ouvert", "gravite": "élevé" },
  { "equipement_id": 4, "description": "Erreur RAID", "statut": "ouvert", "gravite": "critique" },
  { "equipement_id": 5, "description": "Routeur reboot tout seul", "statut": "résolu", "gravite": "moyen" },
  { "equipement_id": 6, "description": "Batterie faible", "statut": "ouvert", "gravite": "faible" },
  { "equipement_id": 7, "description": "Impossible d’imprimer", "statut": "ouvert", "gravite": "moyen" },
  { "equipement_id": 8, "description": "Défaut d’alimentation", "statut": "résolu", "gravite": "élevé" },
  { "equipement_id": 9, "description": "Écran qui scintille", "statut": "ouvert", "gravite": "faible" },
  { "equipement_id": 10, "description": "Carte réseau défectueuse", "statut": "ouvert", "gravite": "critique" },
  { "equipement_id": 11, "description": "USB non détecté", "statut": "ouvert", "gravite": "moyen" },
  { "equipement_id": 12, "description": "Impression lente", "statut": "ouvert", "gravite": "faible" },
  { "equipement_id": 13, "description": "Problème de ventilation", "statut": "ouvert", "gravite": "élevé" },
  { "equipement_id": 14, "description": "RAM défectueuse", "statut": "résolu", "gravite": "critique" },
  { "equipement_id": 15, "description": "Blocage système", "statut": "ouvert", "gravite": "élevé" },
  { "equipement_id": 16, "description": "Scanner non détecté", "statut": "résolu", "gravite": "faible" },
  { "equipement_id": 17, "description": "Chargeur cassé", "statut": "ouvert", "gravite": "faible" },
  { "equipement_id": 18, "description": "Lenteur globale", "statut": "ouvert", "gravite": "moyen" },
  { "equipement_id": 19, "description": "Firmware obsolète", "statut": "ouvert", "gravite": "moyen" },
  { "equipement_id": 20, "description": "Redémarrage aléatoire", "statut": "ouvert", "gravite": "critique" },
  { "equipement_id": 21, "description": "Surchauffe détectée", "statut": "ouvert", "gravite": "élevé" },
  { "equipement_id": 22, "description": "Disque dur plein", "statut": "ouvert", "gravite": "moyen" },
  { "equipement_id": 23, "description": "Pas de son", "statut": "résolu", "gravite": "faible" },
  { "equipement_id": 24, "description": "Imprimante indisponible", "statut": "ouvert", "gravite": "élevé" },
  { "equipement_id": 25, "description": "Clavier non reconnu", "statut": "ouvert", "gravite": "faible" },
  { "equipement_id": 26, "description": "Connexion WiFi instable", "statut": "ouvert", "gravite": "moyen" },
  { "equipement_id": 27, "description": "Erreur système", "statut": "ouvert", "gravite": "critique" },
  { "equipement_id": 28, "description": "Alimentation défectueuse", "statut": "résolu", "gravite": "moyen" },
  { "equipement_id": 29, "description": "Ports Ethernet HS", "statut": "ouvert", "gravite": "élevé" },
  { "equipement_id": 30, "description": "Affichage lent", "statut": "ouvert", "gravite": "faible" }
];

module.exports = incidents;