const maintenances = [
  { "equipement_id": 1, "type": "préventive", "commentaire": "Nettoyage interne complet", "date_maintenance": "2025-01-03" },
  { "equipement_id": 2, "type": "corrective", "commentaire": "Remplacement du toner", "date_maintenance": "2025-01-04" },
  { "equipement_id": 3, "type": "corrective", "commentaire": "Réinstallation de l’OS", "date_maintenance": "2025-01-05" },
  { "equipement_id": 4, "type": "préventive", "commentaire": "Contrôle RAID serveur", "date_maintenance": "2025-01-06" },
  { "equipement_id": 5, "type": "corrective", "commentaire": "Reconfiguration du routeur", "date_maintenance": "2025-01-07" },
  { "equipement_id": 6, "type": "préventive", "commentaire": "Nettoyage clavier et écran", "date_maintenance": "2025-01-08" },
  { "equipement_id": 7, "type": "corrective", "commentaire": "Changement tête d’impression", "date_maintenance": "2025-01-09" },
  { "equipement_id": 8, "type": "préventive", "commentaire": "Mise à jour du firmware écran", "date_maintenance": "2025-01-10" },
  { "equipement_id": 9, "type": "corrective", "commentaire": "Changement rouleau d’impression", "date_maintenance": "2025-01-11" },
  { "equipement_id": 10, "type": "corrective", "commentaire": "Réparation port LAN", "date_maintenance": "2025-01-12" },
  { "equipement_id": 11, "type": "préventive", "commentaire": "Vérification batterie", "date_maintenance": "2025-01-13" },
  { "equipement_id": 12, "type": "corrective", "commentaire": "Nettoyage têtes d’encre", "date_maintenance": "2025-01-14" },
  { "equipement_id": 13, "type": "corrective", "commentaire": "Remplacement câble HDMI", "date_maintenance": "2025-01-15" },
  { "equipement_id": 14, "type": "préventive", "commentaire": "Diagnostic complet BIOS", "date_maintenance": "2025-01-16" },
  { "equipement_id": 15, "type": "corrective", "commentaire": "Mise à jour FortiOS", "date_maintenance": "2025-01-17" },
  { "equipement_id": 16, "type": "corrective", "commentaire": "Remplacement de RAM", "date_maintenance": "2025-01-18" },
  { "equipement_id": 17, "type": "préventive", "commentaire": "Alignement optique scanner", "date_maintenance": "2025-01-19" },
  { "equipement_id": 18, "type": "corrective", "commentaire": "Réinstallation pilotes", "date_maintenance": "2025-01-20" },
  { "equipement_id": 19, "type": "préventive", "commentaire": "Changement unité de fusion", "date_maintenance": "2025-01-21" },
  { "equipement_id": 20, "type": "corrective", "commentaire": "Dépoussiérage ventilateur", "date_maintenance": "2025-01-22" },
  { "equipement_id": 21, "type": "préventive", "commentaire": "Vérification SSD et HDD", "date_maintenance": "2025-01-23" },
  { "equipement_id": 22, "type": "corrective", "commentaire": "Nettoyage connectiques", "date_maintenance": "2025-01-24" },
  { "equipement_id": 23, "type": "corrective", "commentaire": "Mise à jour firmware Wi-Fi", "date_maintenance": "2025-01-25" },
  { "equipement_id": 24, "type": "préventive", "commentaire": "Contrôle alimentation", "date_maintenance": "2025-01-26" },
  { "equipement_id": 25, "type": "corrective", "commentaire": "Changement d’alimentation", "date_maintenance": "2025-01-27" },
  { "equipement_id": 26, "type": "préventive", "commentaire": "Nettoyage externe", "date_maintenance": "2025-01-28" },
  { "equipement_id": 27, "type": "corrective", "commentaire": "Réparation carte mère", "date_maintenance": "2025-01-29" },
  { "equipement_id": 28, "type": "préventive", "commentaire": "Test mémoire", "date_maintenance": "2025-01-30" },
  { "equipement_id": 29, "type": "corrective", "commentaire": "Reprogrammation firmware", "date_maintenance": "2025-01-31" },
  { "equipement_id": 30, "type": "préventive", "commentaire": "Inspection de sécurité", "date_maintenance": "2025-02-01" }
];

module.exports = maintenances;