const utilisateurs = [
  { "nom": "Alice Dupont", "email": "alice1@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 1 },
  { "nom": "Bob Martin", "email": "bob2@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 2 },
  { "nom": "Clara Leroy", "email": "clara3@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "David Morel", "email": "david4@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 2 },
  { "nom": "Eva Petit", "email": "eva5@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Franck Simon", "email": "franck6@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Gwen Dubois", "email": "gwen7@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Hugo Lemoine", "email": "hugo8@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 2 },
  { "nom": "Isabelle Blanc", "email": "isabelle9@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Jacques Millet", "email": "jacques10@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Karine Chevalier", "email": "karine11@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 2 },
  { "nom": "Louis Gerard", "email": "louis12@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Manon Mercier", "email": "manon13@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Nina Lefevre", "email": "nina14@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Olivier Caron", "email": "olivier15@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 2 },
  { "nom": "Pauline Roche", "email": "pauline16@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Quentin Renaud", "email": "quentin17@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Romain Marchand", "email": "romain18@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 2 },
  { "nom": "Sophie Noel", "email": "sophie19@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Thomas Bonnet", "email": "thomas20@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Ugo Hardy", "email": "ugo21@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Valerie Fabre", "email": "valerie22@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 2 },
  { "nom": "William Roy", "email": "william23@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Xavier Colin", "email": "xavier24@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 2 },
  { "nom": "Yasmine Garnier", "email": "yasmine25@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Zacharie Muller", "email": "zacharie26@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Anais Lambert", "email": "anais27@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Bruno Lemoine", "email": "bruno28@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Camille Joly", "email": "camille29@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 },
  { "nom": "Damien Berger", "email": "damien30@assetium.com", "mot_de_passe": "hashedpwd", "role_id": 3 }
];

module.exports = utilisateurs;